markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
url: http://ow2.github.com/ow2-technologycouncil-blog/
#url: http://localhost:4000
#ga: UA-26468797-1
disqus: ow2tcblog
twitter: ow2tc
title: OW2 TC.blog
author: OW2 Technology Council
